name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gtk dependencies
      run: sudo apt install libgtk-3-dev libmount-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
